// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAflhm_XZqonmTeaVk2gzpaqLZtKkrYlh0',
    appId: '1:255882412900:web:8183c248df7e85ff9b3071',
    messagingSenderId: '255882412900',
    projectId: 'shamo-073',
    authDomain: 'shamo-073.firebaseapp.com',
    storageBucket: 'shamo-073.appspot.com',
    measurementId: 'G-HRMZCR9R46',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_z6NsGGV7SO-_O0d8fUdDq9Q2RSQge0M',
    appId: '1:255882412900:android:920c9a6b3024592c9b3071',
    messagingSenderId: '255882412900',
    projectId: 'shamo-073',
    storageBucket: 'shamo-073.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGrnlmSEqM6dsAV4Y-oRVyHIAoF1iVC9w',
    appId: '1:255882412900:ios:96a8c4c827d9a5949b3071',
    messagingSenderId: '255882412900',
    projectId: 'shamo-073',
    storageBucket: 'shamo-073.appspot.com',
    iosClientId: '255882412900-17hr77k5vooaeod5h8r3t5ko00sortuc.apps.googleusercontent.com',
    iosBundleId: 'com.mfr073.shamoApps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGrnlmSEqM6dsAV4Y-oRVyHIAoF1iVC9w',
    appId: '1:255882412900:ios:4c47961debd79ee99b3071',
    messagingSenderId: '255882412900',
    projectId: 'shamo-073',
    storageBucket: 'shamo-073.appspot.com',
    iosClientId: '255882412900-2ffenjjv8cprodh08rei7jjpva3j8foj.apps.googleusercontent.com',
    iosBundleId: 'com.example.shamoApps',
  );
}
